# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0846244ada63d283c5300d8fbd7cf70752feb384f4ed8eae7bdac2c3c98bd483ffcf6973a760db5b5adc25e0990d48741ceadfe474ae5e649e0f2b26d287b02

test:
  secret_key_base: 435b8a50d73b38224a05693e7133e46d8b831b5924fb300d846f207531416a83ea44185db2b5e5e531568252f495cbde632932b9a3b02de0bec4b00713982e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
